### ISSUE TITLE
Add validation for room-id

### ISSUE THREAD

**Issue by ComradeVanti** [PartyHubAT/app#3]
**Is your feature request related to a problem? Please describe.**
Room-ids have a very specific length of 6 digits. Currently this is not indicated on the UI.

**Describe the solution you'd like**
Add a validator, that tells the user, if the room-id is too long or too short.

**Describe alternatives you've considered**
We could also just add a label that says "6-digit room-id" or similar.

**Comment by lukasganster** [comment]
Done with commit d77ea1a
